# Generated by Django 4.1.5 on 2023-03-06 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_work', models.CharField(help_text='Не больше 255 символов', max_length=255, null=True)),
                ('img_background_work', models.ImageField(upload_to='')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_changes', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HashtagsName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(help_text='Не больше 50 символов', max_length=50, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_changes', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_changes', models.DateTimeField(auto_now=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_galirey.gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Hashtags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_changes', models.DateTimeField(auto_now=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_galirey.gallery')),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_galirey.hashtagsname')),
            ],
        ),
    ]
