# Generated by Django 4.1.5 on 2023-03-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_galirey', '0002_services_specificsservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.IntegerField(help_text='Не больше 255 цифр', null=True),
        ),
    ]
