# Generated by Django 4.1.5 on 2023-03-19 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_galirey', '0003_alter_services_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificsservices',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_galirey.services'),
        ),
    ]
