# Generated by Django 4.1.5 on 2023-03-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_galirey', '0004_alter_specificsservices_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_faq', models.CharField(help_text='Не больше 255 символов', max_length=255, null=True)),
                ('description', models.CharField(help_text='Не больше 100 символов', max_length=1000, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_changes', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
