# Generated by Django 4.1.5 on 2023-03-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_galirey', '0005_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='description',
            field=models.TextField(help_text='Не больше 1000 символов', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(help_text='Не больше 255 символов', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='question_price',
            field=models.TextField(help_text='Не больше 255 символов', max_length=255, null=True),
        ),
    ]
