# Generated by Django 4.1.5 on 2023-03-23 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_galirey', '0006_alter_faq_description_alter_services_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('name_reviewer', models.CharField(help_text='Не больше 255 символов', max_length=255, null=True)),
                ('review', models.TextField(help_text='Не больше 1000 символов', max_length=1000, null=True)),
                ('img_reviewer', models.ImageField(upload_to='')),
                ('social_networks', models.CharField(help_text='Не больше 255 символов', max_length=255, null=True)),
                ('gallery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='photo_galirey.gallery')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_changes', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
