# Generated by Django 4.1.5 on 2023-03-30 07:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_galirey', '0007_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call', models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(regex='\\+7 \\(\\d{3}\\) \\d{3}-\\d{2}-\\d{2}')])),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True, max_length=1000, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_galirey.services')),
            ],
        ),
    ]
