# Generated by Django 4.1.5 on 2023-04-13 17:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_galirey', '0010_ordercall'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['id'], 'verbose_name': 'Часто задаваемые вопросы', 'verbose_name_plural': 'Часто задаваемые вопросы'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['id'], 'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбомы'},
        ),
        migrations.AlterModelOptions(
            name='hashtags',
            options={'ordering': ['id'], 'verbose_name': 'Альбомы и их категории', 'verbose_name_plural': 'Альбомы и их категории'},
        ),
        migrations.AlterModelOptions(
            name='hashtagsname',
            options={'ordering': ['id'], 'verbose_name': 'Существующая категория', 'verbose_name_plural': 'Существующие категории'},
        ),
        migrations.AlterModelOptions(
            name='img',
            options={'ordering': ['gallery'], 'verbose_name': 'Фотография в альбомах', 'verbose_name_plural': 'Фотографии в альбомах'},
        ),
        migrations.AlterModelOptions(
            name='ordercall',
            options={'ordering': ['id'], 'verbose_name': 'Заказанные звонки', 'verbose_name_plural': 'Заказанные звонки'},
        ),
        migrations.AlterModelOptions(
            name='orderservice',
            options={'ordering': ['service'], 'verbose_name': 'Заказанные услуги', 'verbose_name_plural': 'Заказанные услуги'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['gallery'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['id'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='specificsservices',
            options={'ordering': ['services'], 'verbose_name': 'Основные пункты услуги', 'verbose_name_plural': 'Основные пункты услуги'},
        ),
        migrations.AddField(
            model_name='ordercall',
            name='date_changes',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AddField(
            model_name='ordercall',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default='2019-09-25 06:00', verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderservice',
            name='date_changes',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AddField(
            model_name='orderservice',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default='2019-09-25 06:00', verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faq',
            name='date_changes',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='description',
            field=models.TextField(help_text='Не больше 1000 символов', max_length=1000, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='name_faq',
            field=models.CharField(help_text='Не больше 255 символов', max_length=255, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='publication',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='date_changes',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='img_background_work',
            field=models.ImageField(upload_to='', verbose_name='Обложка альбома'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='name_work',
            field=models.CharField(help_text='Не больше 255 символов', max_length=255, null=True, verbose_name='Название альбома'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='publication',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='hashtags',
            name='date_changes',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='hashtags',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='hashtags',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_galirey.gallery', verbose_name='Альбом'),
        ),
        migrations.AlterField(
            model_name='hashtags',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_galirey.hashtagsname', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='hashtagsname',
            name='date_changes',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='hashtagsname',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='hashtagsname',
            name='hashtag',
            field=models.CharField(help_text='Не больше 50 символов', max_length=50, null=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='img',
            name='date_changes',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='img',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='img',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_galirey.gallery', verbose_name='Альбом'),
        ),
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='ordercall',
            name='call',
            field=models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(regex='\\+7 \\(\\d{3}\\) \\d{3}-\\d{2}-\\d{2}')], verbose_name='Номер телефона клиента'),
        ),
        migrations.AlterField(
            model_name='ordercall',
            name='message',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='ordercall',
            name='name',
            field=models.CharField(max_length=50, verbose_name='ФИО клиента'),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='call',
            field=models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(regex='\\+7 \\(\\d{3}\\) \\d{3}-\\d{2}-\\d{2}')], verbose_name='Номер телефона клиента'),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта клиента'),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='message',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='name',
            field=models.CharField(max_length=50, verbose_name='ФИО клиента'),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_galirey.services', verbose_name='Заказанная услуга'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_changes',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='img_reviewer',
            field=models.ImageField(upload_to='', verbose_name='Фотография клиента'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name_reviewer',
            field=models.CharField(help_text='Не больше 255 символов', max_length=255, null=True, verbose_name='ФИО клиента'),
        ),
        migrations.AlterField(
            model_name='review',
            name='publication',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(help_text='Не больше 1000 символов', max_length=1000, null=True, verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='review',
            name='social_networks',
            field=models.CharField(help_text='Не больше 255 символов', max_length=255, null=True, verbose_name='Социальные сети клиента'),
        ),
        migrations.AlterField(
            model_name='services',
            name='date_changes',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='services',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(help_text='Не больше 255 символов', max_length=255, null=True, verbose_name='Описание услуги'),
        ),
        migrations.AlterField(
            model_name='services',
            name='img_background_services',
            field=models.ImageField(upload_to='', verbose_name='Изображение на заднем фоне'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name_services',
            field=models.CharField(help_text='Не больше 255 символов', max_length=255, null=True, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.IntegerField(help_text='Не больше 255 цифр', null=True, verbose_name='Цена руб.'),
        ),
        migrations.AlterField(
            model_name='services',
            name='publication',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='services',
            name='question_price',
            field=models.TextField(help_text='Не больше 255 символов', max_length=255, null=True, verbose_name='Обоснование цены'),
        ),
        migrations.AlterField(
            model_name='specificsservices',
            name='date_changes',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='specificsservices',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='specificsservices',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_galirey.services', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='specificsservices',
            name='specifics',
            field=models.CharField(help_text='Не больше 255 символов', max_length=255, null=True, verbose_name='Основной пункт'),
        ),
    ]
